import type { WorkflowNodeTemplate } from "../types";

export const node: WorkflowNodeTemplate = {
  id: "s3_object",
  title: "S3 Object",
  description: "Put/get objects and generate presigned links",
  category: "Data",
  defaultConfig: {
    action: "put",
    endpoint: "http://localhost:9000",
    bucket: "incidenthub-artifacts",
    region: "us-east-1",
    accessKeyId: "",
    secretAccessKey: "",
    pathStyle: true,
    useSSL: false,
    key: "workflows/{{workflow_id}}/{{run_id}}.json",
    body: "{{payload}}",
    contentType: "application/json",
    ttlSeconds: 900,
    maxBytes: 1048576,
  },
  fields: [
    {
      id: "action",
      label: "Action",
      type: "select",
      options: [
        { label: "Put object", value: "put" },
        { label: "Get object", value: "get" },
        { label: "Presign GET URL", value: "presign_get" },
      ],
    },
    {
      id: "endpoint",
      label: "Endpoint",
      type: "text",
      placeholder: "http://localhost:9000",
    },
    {
      id: "bucket",
      label: "Bucket",
      type: "text",
      placeholder: "incidenthub-artifacts",
    },
    {
      id: "region",
      label: "Region",
      type: "text",
      placeholder: "us-east-1",
    },
    {
      id: "accessKeyId",
      label: "Access key ID",
      type: "text",
      placeholder: "AKIA...",
      sensitive: true,
    },
    {
      id: "secretAccessKey",
      label: "Secret access key",
      type: "text",
      placeholder: "secret",
      sensitive: true,
    },
    {
      id: "sessionToken",
      label: "Session token",
      type: "text",
      placeholder: "optional",
      sensitive: true,
    },
    {
      id: "pathStyle",
      label: "Path style",
      type: "switch",
    },
    {
      id: "useSSL",
      label: "Use SSL",
      type: "switch",
    },
    {
      id: "key",
      label: "Object key",
      type: "text",
      placeholder: "workflows/{{workflow_id}}/{{run_id}}.json",
    },
    {
      id: "body",
      label: "Body template",
      type: "textarea",
      placeholder: "{\"run\":\"{{run_id}}\"}",
      when: { field: "action", equals: "put" },
    },
    {
      id: "contentType",
      label: "Content type",
      type: "text",
      placeholder: "application/json",
      when: { field: "action", equals: "put" },
    },
    {
      id: "ttlSeconds",
      label: "Presign TTL (seconds)",
      type: "number",
      min: 60,
      max: 86400,
      step: 1,
      when: { field: "action", equals: "presign_get" },
    },
    {
      id: "maxBytes",
      label: "Max bytes to read",
      type: "number",
      min: 1024,
      max: 10485760,
      step: 1024,
      when: { field: "action", equals: "get" },
    },
  ],
  summaryField: "action",
  summaryFallback: "configured",
};
