package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func writeReportFiles(path string, report loadReport) (jsonPath string, markdownPath string, err error) {
	jsonPath = strings.TrimSpace(path)
	if jsonPath == "" {
		return "", "", fmt.Errorf("output path cannot be empty")
	}

	if mkdirErr := os.MkdirAll(filepath.Dir(jsonPath), 0755); mkdirErr != nil {
		return "", "", fmt.Errorf("create report directory: %w", mkdirErr)
	}

	rawJSON, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return "", "", fmt.Errorf("marshal report: %w", err)
	}
	if writeErr := os.WriteFile(jsonPath, rawJSON, 0o600); writeErr != nil {
		return "", "", fmt.Errorf("write json report: %w", writeErr)
	}

	markdownPath = strings.TrimSuffix(jsonPath, filepath.Ext(jsonPath)) + ".md"
	if writeErr := os.WriteFile(markdownPath, []byte(renderMarkdown(report)), 0o600); writeErr != nil {
		return "", "", fmt.Errorf("write markdown report: %w", writeErr)
	}
	return jsonPath, markdownPath, nil
}

func renderMarkdown(report loadReport) string {
	builder := strings.Builder{}
	builder.WriteString("# IncidentHub Load Test Report\n\n")
	_, _ = fmt.Fprintf(&builder, "- Generated at (UTC): `%s`\n", report.GeneratedAtUTC)
	_, _ = fmt.Fprintf(&builder, "- Base URL: `%s`\n", report.BaseURL)
	_, _ = fmt.Fprintf(&builder, "- Tenant ID: `%s`\n", report.TenantID)
	_, _ = fmt.Fprintf(&builder, "- Step duration: `%s`\n", report.StepDuration)
	_, _ = fmt.Fprintf(&builder, "- Cooldown: `%s`\n", report.Cooldown)
	_, _ = fmt.Fprintf(&builder, "- Workers: `%d`\n", report.Workers)
	_, _ = fmt.Fprintf(&builder, "- Error threshold: `%.4f`\n", report.ErrorThreshold)
	_, _ = fmt.Fprintf(&builder, "- P95 threshold: `%.3f ms`\n\n", report.P95ThresholdMS)

	for _, scenario := range report.Scenarios {
		_, _ = fmt.Fprintf(&builder, "## %s\n\n", scenario.Name)
		_, _ = fmt.Fprintf(&builder, "- Category: `%s`\n", scenario.Category)
		_, _ = fmt.Fprintf(&builder, "- Route: `%s %s`\n", scenario.Method, scenario.PathTemplate)
		_, _ = fmt.Fprintf(&builder, "- Max sustainable RPS: `%d`\n\n", scenario.MaxSustainableRPS)
		builder.WriteString("| Target RPS | Achieved RPS | Total | Success % | Error % | p95 ms | Pass |\n")
		builder.WriteString("|---:|---:|---:|---:|---:|---:|:---:|\n")
		for _, step := range scenario.Steps {
			passCell := "yes"
			if !step.Passed {
				passCell = "no"
			}
			_, _ = fmt.Fprintf(&builder,
				"| %d | %.2f | %d | %.2f | %.2f | %.2f | %s |\n",
				step.TargetRPS,
				step.AchievedRPS,
				step.TotalRequests,
				step.SuccessRate*100.0,
				step.ErrorRate*100.0,
				step.P95LatencyMS,
				passCell,
			)
		}
		builder.WriteString("\n")
	}

	builder.WriteString("## Route Summary\n\n")
	type summaryLine struct {
		Name     string
		Category string
		MaxRPS   int
	}
	lines := make([]summaryLine, 0, len(report.Scenarios))
	for _, item := range report.Scenarios {
		lines = append(lines, summaryLine{Name: item.Name, Category: item.Category, MaxRPS: item.MaxSustainableRPS})
	}
	sort.Slice(lines, func(i, j int) bool {
		if lines[i].Category == lines[j].Category {
			return lines[i].Name < lines[j].Name
		}
		return lines[i].Category < lines[j].Category
	})
	for _, line := range lines {
		_, _ = fmt.Fprintf(&builder, "- [%s] %s: `%d` RPS\n", strings.ToUpper(line.Category), line.Name, line.MaxRPS)
	}
	builder.WriteString("\n")
	_, _ = fmt.Fprintf(&builder, "_Generated by backend/tools/loadtest at %s_\n", time.Now().UTC().Format(time.RFC3339))
	return builder.String()
}
