import type { WorkflowNodeTemplate } from "../types";

export const node: WorkflowNodeTemplate = {
  id: "redis",
  title: "Redis",
  description: "Read/write Redis keys and queue lists",
  category: "Data",
  defaultConfig: {
    operation: "set",
    addr: "localhost:6379",
    db: 0,
    key: "incidenthub:workflow:key",
    value: "{{input.case_id}}",
    ttlSeconds: 0,
    useTLS: false,
    skipTLSVerify: false,
    timeoutSeconds: 10,
  },
  fields: [
    {
      id: "operation",
      label: "Operation",
      type: "select",
      options: [
        { label: "SET", value: "set" },
        { label: "GET", value: "get" },
        { label: "DEL", value: "del" },
        { label: "INCR", value: "incr" },
        { label: "LPUSH", value: "lpush" },
        { label: "RPUSH", value: "rpush" },
        { label: "LPOP", value: "lpop" },
        { label: "RPOP", value: "rpop" },
      ],
    },
    {
      id: "url",
      label: "Redis URL",
      type: "text",
      placeholder: "redis://user:password@localhost:6379/0",
      sensitive: true,
    },
    {
      id: "addr",
      label: "Addr",
      type: "text",
      placeholder: "localhost:6379",
    },
    {
      id: "db",
      label: "DB",
      type: "number",
      min: 0,
      max: 64,
      step: 1,
    },
    {
      id: "username",
      label: "Username",
      type: "text",
      placeholder: "optional",
      sensitive: true,
    },
    {
      id: "password",
      label: "Password",
      type: "text",
      placeholder: "optional",
      sensitive: true,
    },
    {
      id: "key",
      label: "Key",
      type: "text",
      placeholder: "incidenthub:workflow:key",
    },
    {
      id: "value",
      label: "Value template",
      type: "textarea",
      placeholder: "{{input.case_id}}",
      description: "Used in set/lpush/rpush",
    },
    {
      id: "ttlSeconds",
      label: "TTL (seconds)",
      type: "number",
      min: 0,
      max: 86400,
      step: 1,
      when: { field: "operation", equals: "set" },
    },
    {
      id: "timeoutSeconds",
      label: "Timeout (seconds)",
      type: "number",
      min: 1,
      max: 120,
      step: 1,
    },
    {
      id: "useTLS",
      label: "Use TLS",
      type: "switch",
    },
    {
      id: "skipTLSVerify",
      label: "Skip TLS verify",
      type: "switch",
      when: { field: "useTLS", equals: true },
    },
  ],
  summaryField: "operation",
  summaryFallback: "configured",
};
