import type { WorkflowNodeTemplate } from "../types";

export const node: WorkflowNodeTemplate = {
  id: "cassandra_query",
  title: "Cassandra Query",
  description: "Execute CQL over Cassandra HTTP gateway",
  category: "Data",
  defaultConfig: {
    endpoint: "http://localhost:8082/v2/cql",
    query: "SELECT * FROM incidents WHERE tenant_id = ? LIMIT 20",
    params: "[\"{{tenant_id}}\"]",
    keyspace: "",
    consistency: "LOCAL_QUORUM",
    pageSize: 100,
    timeoutSeconds: 15,
  },
  fields: [
    {
      id: "endpoint",
      label: "Endpoint",
      type: "text",
      placeholder: "http://localhost:8082/v2/cql",
    },
    {
      id: "query",
      label: "CQL query",
      type: "json",
      placeholder: "SELECT * FROM ...",
    },
    {
      id: "params",
      label: "Params (JSON array)",
      type: "json",
      placeholder: "[\"{{input.case_id}}\"]",
    },
    {
      id: "keyspace",
      label: "Keyspace",
      type: "text",
      placeholder: "soc",
    },
    {
      id: "consistency",
      label: "Consistency",
      type: "text",
      placeholder: "LOCAL_QUORUM",
    },
    {
      id: "token",
      label: "Auth token",
      type: "text",
      placeholder: "AstraCS:...",
      sensitive: true,
    },
    {
      id: "headers",
      label: "Headers (JSON object)",
      type: "json",
      placeholder: "{\"X-Cassandra-Token\":\"...\"}",
      sensitive: true,
    },
    {
      id: "pageSize",
      label: "Page size",
      type: "number",
      min: 1,
      max: 5000,
      step: 1,
    },
    {
      id: "timeoutSeconds",
      label: "Timeout (seconds)",
      type: "number",
      min: 1,
      max: 120,
      step: 1,
    },
  ],
  summaryFallback: "CQL configured",
};
